<?php

/**
 * BaseUserChannel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $role_id
 * @property integer $channel_id
 * 
 * @method integer     getUserId()     Returns the current record's "user_id" value
 * @method integer     getRoleId()     Returns the current record's "role_id" value
 * @method integer     getChannelId()  Returns the current record's "channel_id" value
 * @method UserChannel setUserId()     Sets the current record's "user_id" value
 * @method UserChannel setRoleId()     Sets the current record's "role_id" value
 * @method UserChannel setChannelId()  Sets the current record's "channel_id" value
 * 
 * @package    LoveToKnow
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseUserChannel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_channel');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('role_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('channel_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('user', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}