<?php

/**
 * BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $channel_id
 * @property integer $title_id
 * @property Article $Article
 * @property Channel $Channel
 * @property Doctrine_Collection $Titles
 * 
 * @method integer             getChannelId()  Returns the current record's "channel_id" value
 * @method integer             getTitleId()    Returns the current record's "title_id" value
 * @method Article             getArticle()    Returns the current record's "Article" value
 * @method Channel             getChannel()    Returns the current record's "Channel" value
 * @method Doctrine_Collection getTitles()     Returns the current record's "Titles" collection
 * @method Category            setChannelId()  Sets the current record's "channel_id" value
 * @method Category            setTitleId()    Sets the current record's "title_id" value
 * @method Category            setArticle()    Sets the current record's "Article" value
 * @method Category            setChannel()    Sets the current record's "Channel" value
 * @method Category            setTitles()     Sets the current record's "Titles" collection
 * 
 * @package    LoveToKnow
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('channel_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title_id', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('title', array(
             'fields' => 
             array(
              0 => 'title_id',
              1 => 'channel_id',
             ),
             'type' => 'unique',
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Article', array(
             'local' => 'title_id',
             'foreign' => 'title_id'));

        $this->hasOne('Channel', array(
             'local' => 'channel_id',
             'foreign' => 'id'));

        $this->hasMany('Title as Titles', array(
             'refClass' => 'TitleCategory',
             'local' => 'category_id',
             'foreign' => 'title_id'));

        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => true,
             'rootColumnName' => 'channel_id',
             ));
        $derivative0 = new Derivative(array(
             'base' => 'Title',
             ));
        $auditable0 = new Auditable();
        $this->actAs($nestedset0);
        $this->actAs($derivative0);
        $this->actAs($auditable0);
    }
}