<?php

/**
 * BaseSlideshow
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $show_home_page
 * @property Doctrine_Collection $Slides
 * 
 * @method integer             getShowHomePage()   Returns the current record's "show_home_page" value
 * @method Doctrine_Collection getSlides()         Returns the current record's "Slides" collection
 * @method Slideshow           setShowHomePage()   Sets the current record's "show_home_page" value
 * @method Slideshow           setSlides()         Sets the current record's "Slides" collection
 * 
 * @package    LoveToKnow
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseSlideshow extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('slideshow');
        $this->hasColumn('show_home_page', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => '1',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Slide as Slides', array(
             'local' => 'id',
             'foreign' => 'slideshow_id'));

        $derivative0 = new Derivative(array(
             'base' => 'Title',
             ));
        $auditable0 = new Auditable();
        $this->actAs($derivative0);
        $this->actAs($auditable0);
    }
}