<?php

/**
 * BaseFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $channel_id
 * @property string $host
 * @property string $path
 * @property string $filename
 * @property string $source
 * @property string $permission
 * @property clob $description
 * @property Channel $Channel
 * 
 * @method integer getChannelId()   Returns the current record's "channel_id" value
 * @method string  getHost()        Returns the current record's "host" value
 * @method string  getPath()        Returns the current record's "path" value
 * @method string  getFilename()    Returns the current record's "filename" value
 * @method string  getSource()      Returns the current record's "source" value
 * @method string  getPermission()  Returns the current record's "permission" value
 * @method clob    getDescription() Returns the current record's "description" value
 * @method Channel getChannel()     Returns the current record's "Channel" value
 * @method File    setChannelId()   Sets the current record's "channel_id" value
 * @method File    setHost()        Sets the current record's "host" value
 * @method File    setPath()        Sets the current record's "path" value
 * @method File    setFilename()    Sets the current record's "filename" value
 * @method File    setSource()      Sets the current record's "source" value
 * @method File    setPermission()  Sets the current record's "permission" value
 * @method File    setDescription() Sets the current record's "description" value
 * @method File    setChannel()     Sets the current record's "Channel" value
 * 
 * @package    LoveToKnow
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseFile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('file');
        $this->hasColumn('channel_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('host', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('path', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('filename', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('source', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('permission', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Channel', array(
             'local' => 'channel_id',
             'foreign' => 'id'));
    }
}