<?php

/**
 * BaseFeatureArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $channel_id
 * @property integer $category_id
 * @property integer $article_id
 * @property enum $position
 * @property Channel $Channel
 * @property Title $Title
 * 
 * @method integer        getChannelId()   Returns the current record's "channel_id" value
 * @method integer        getCategoryId()  Returns the current record's "category_id" value
 * @method integer        getArticleId()   Returns the current record's "article_id" value
 * @method enum           getPosition()    Returns the current record's "position" value
 * @method Channel        getChannel()     Returns the current record's "Channel" value
 * @method Title          getTitle()       Returns the current record's "Title" value
 * @method FeatureArticle setChannelId()   Sets the current record's "channel_id" value
 * @method FeatureArticle setCategoryId()  Sets the current record's "category_id" value
 * @method FeatureArticle setArticleId()   Sets the current record's "article_id" value
 * @method FeatureArticle setPosition()    Sets the current record's "position" value
 * @method FeatureArticle setChannel()     Sets the current record's "Channel" value
 * @method FeatureArticle setTitle()       Sets the current record's "Title" value
 * 
 * @package    LoveToKnow
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseFeatureArticle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('feature_article');
        $this->hasColumn('channel_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('article_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('position', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Above',
              1 => 'Below',
              2 => 'Right',
             ),
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Channel', array(
             'local' => 'channel_id',
             'foreign' => 'id'));

        $this->hasOne('Title', array(
             'local' => 'article_id',
             'foreign' => 'id'));
    }
}