<?php

/**
 * BaseSlide
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $slideshow_id
 * @property integer $rank
 * @property integer $image_id
 * @property string $image_link
 * @property string $heading
 * @property clob $text
 * @property Slideshow $Slideshow
 * @property Image $Image
 * 
 * @method integer   getSlideshowId()  Returns the current record's "slideshow_id" value
 * @method integer   getRank()         Returns the current record's "rank" value
 * @method integer   getImageId()      Returns the current record's "image_id" value
 * @method string    getImageLink()    Returns the current record's "image_link" value
 * @method string    getHeading()      Returns the current record's "heading" value
 * @method clob      getText()         Returns the current record's "text" value
 * @method Slideshow getSlideshow()    Returns the current record's "Slideshow" value
 * @method Image     getImage()        Returns the current record's "Image" value
 * @method Slide     setSlideshowId()  Sets the current record's "slideshow_id" value
 * @method Slide     setRank()         Sets the current record's "rank" value
 * @method Slide     setImageId()      Sets the current record's "image_id" value
 * @method Slide     setImageLink()    Sets the current record's "image_link" value
 * @method Slide     setHeading()      Sets the current record's "heading" value
 * @method Slide     setText()         Sets the current record's "text" value
 * @method Slide     setSlideshow()    Sets the current record's "Slideshow" value
 * @method Slide     setImage()        Sets the current record's "Image" value
 * 
 * @package    LoveToKnow
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseSlide extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('slide');
        $this->hasColumn('slideshow_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('rank', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('image_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('image_link', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('heading', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('text', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));


        $this->index('rank', array(
             'fields' => 
             array(
              0 => 'slideshow_id',
              1 => 'rank',
             ),
             'type' => 'unique',
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Slideshow', array(
             'local' => 'slideshow_id',
             'foreign' => 'id'));

        $this->hasOne('Image', array(
             'local' => 'image_id',
             'foreign' => 'id'));

        $auditable0 = new Auditable();
        $this->actAs($auditable0);
    }
}