<?php

/**
 * BaseArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property clob $text
 * @property integer $show_home_page
 * @property clob $related_article_urls
 * 
 * @method clob    getText()                 Returns the current record's "text" value
 * @method integer getShowHomePage()         Returns the current record's "show_home_page" value
 * @method clob    getRelatedArticleUrls()   Returns the current record's "related_article_urls" value
 * @method Article setText()                 Sets the current record's "text" value
 * @method Article setShowHomePage()         Sets the current record's "show_home_page" value
 * @method Article setRelatedArticleUrls()   Sets the current record's "related_article_urls" value
 * 
 * @package    LoveToKnow
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseArticle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('article');
        $this->hasColumn('text', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('show_home_page', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => '1',
             ));
        $this->hasColumn('related_article_urls', 'clob', null, array(
             'type' => 'clob',
             ));


        $this->index('title', array(
             'fields' => 
             array(
              0 => 'title_id',
             ),
             'type' => 'unique',
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $derivative0 = new Derivative(array(
             'base' => 'Title',
             ));
        $auditable0 = new Auditable();
        $this->actAs($derivative0);
        $this->actAs($auditable0);
    }
}