<?php

/**
 * BaseChannel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $vertical_id
 * @property string $title
 * @property string $short_title
 * @property string $slug
 * @property array $settings
 * @property clob $content
 * @property Vertical $Vertical
 * @property ChannelDetails $Details
 * @property Doctrine_Collection $FeatureArticle
 * 
 * @method integer             getVerticalId()     Returns the current record's "vertical_id" value
 * @method string              getTitle()          Returns the current record's "title" value
 * @method string              getShortTitle()     Returns the current record's "short_title" value
 * @method string              getSlug()           Returns the current record's "slug" value
 * @method array               getSettings()       Returns the current record's "settings" value
 * @method clob                getContent()        Returns the current record's "content" value
 * @method Vertical            getVertical()       Returns the current record's "Vertical" value
 * @method ChannelDetails      getDetails()        Returns the current record's "Details" value
 * @method Doctrine_Collection getFeatureArticle() Returns the current record's "FeatureArticle" collection
 * @method Channel             setVerticalId()     Sets the current record's "vertical_id" value
 * @method Channel             setTitle()          Sets the current record's "title" value
 * @method Channel             setShortTitle()     Sets the current record's "short_title" value
 * @method Channel             setSlug()           Sets the current record's "slug" value
 * @method Channel             setSettings()       Sets the current record's "settings" value
 * @method Channel             setContent()        Sets the current record's "content" value
 * @method Channel             setVertical()       Sets the current record's "Vertical" value
 * @method Channel             setDetails()        Sets the current record's "Details" value
 * @method Channel             setFeatureArticle() Sets the current record's "FeatureArticle" collection
 * 
 * @package    LoveToKnow
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseChannel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('channel');
        $this->hasColumn('vertical_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('short_title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('settings', 'array', null, array(
             'type' => 'array',
             'notnull' => true,
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Vertical', array(
             'local' => 'vertical_id',
             'foreign' => 'id'));

        $this->hasOne('ChannelDetails as Details', array(
             'local' => 'id',
             'foreign' => 'channel_id'));

        $this->hasMany('FeatureArticle', array(
             'local' => 'id',
             'foreign' => 'channel_id'));

        $defaultsort0 = new DefaultSort(array(
             'column' => 'title',
             ));
        $this->actAs($defaultsort0);
    }
}