<?php

/**
 * BaseChannelDetails
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $channel_id
 * @property integer $highlight_title_id
 * @property clob $highlight_content
 * @property integer $popular1_title_id
 * @property clob $popular1_content
 * @property integer $popular2_title_id
 * @property clob $popular2_content
 * @property integer $about_title_id
 * @property Channel $Channel
 * @property Title $Highlight
 * @property Title $Popular1
 * @property Title $Popular2
 * @property Title $AboutChannel
 * 
 * @method integer        getChannelId()          Returns the current record's "channel_id" value
 * @method integer        getHighlightTitleId()   Returns the current record's "highlight_title_id" value
 * @method clob           getHighlightContent()   Returns the current record's "highlight_content" value
 * @method integer        getPopular1TitleId()    Returns the current record's "popular1_title_id" value
 * @method clob           getPopular1Content()    Returns the current record's "popular1_content" value
 * @method integer        getPopular2TitleId()    Returns the current record's "popular2_title_id" value
 * @method clob           getPopular2Content()    Returns the current record's "popular2_content" value
 * @method integer        getAboutTitleId()       Returns the current record's "about_title_id" value
 * @method Channel        getChannel()            Returns the current record's "Channel" value
 * @method Title          getHighlight()          Returns the current record's "Highlight" value
 * @method Title          getPopular1()           Returns the current record's "Popular1" value
 * @method Title          getPopular2()           Returns the current record's "Popular2" value
 * @method Title          getAboutChannel()       Returns the current record's "AboutChannel" value
 * @method ChannelDetails setChannelId()          Sets the current record's "channel_id" value
 * @method ChannelDetails setHighlightTitleId()   Sets the current record's "highlight_title_id" value
 * @method ChannelDetails setHighlightContent()   Sets the current record's "highlight_content" value
 * @method ChannelDetails setPopular1TitleId()    Sets the current record's "popular1_title_id" value
 * @method ChannelDetails setPopular1Content()    Sets the current record's "popular1_content" value
 * @method ChannelDetails setPopular2TitleId()    Sets the current record's "popular2_title_id" value
 * @method ChannelDetails setPopular2Content()    Sets the current record's "popular2_content" value
 * @method ChannelDetails setAboutTitleId()       Sets the current record's "about_title_id" value
 * @method ChannelDetails setChannel()            Sets the current record's "Channel" value
 * @method ChannelDetails setHighlight()          Sets the current record's "Highlight" value
 * @method ChannelDetails setPopular1()           Sets the current record's "Popular1" value
 * @method ChannelDetails setPopular2()           Sets the current record's "Popular2" value
 * @method ChannelDetails setAboutChannel()       Sets the current record's "AboutChannel" value
 * 
 * @package    LoveToKnow
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseChannelDetails extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('channel_details');
        $this->hasColumn('channel_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('highlight_title_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('highlight_content', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('popular1_title_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('popular1_content', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('popular2_title_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('popular2_content', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('about_title_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Channel', array(
             'local' => 'channel_id',
             'foreign' => 'id'));

        $this->hasOne('Title as Highlight', array(
             'local' => 'highlight_title_id',
             'foreign' => 'id'));

        $this->hasOne('Title as Popular1', array(
             'local' => 'popular1_title_id',
             'foreign' => 'id'));

        $this->hasOne('Title as Popular2', array(
             'local' => 'popular2_title_id',
             'foreign' => 'id'));

        $this->hasOne('Title as AboutChannel', array(
             'local' => 'about_title_id',
             'foreign' => 'id'));
    }
}