# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/07-Databases

test:
  doctrine:
    param:
      dsn:      mysql:host=${db.host};dbname=${db.test.name}

all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=${db.host};dbname=${db.name}
      username: ${db.username}
      password: ${db.password}
