<?php

/**
 * Article
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    LoveToKnow
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Article extends BaseArticle
{
   public function preSave($event)
   {
      if(is_null($this->type))
      {
         $this->type = 'Article';
      }
   }
   
   public function getRelatedArticles()
   {
      $relatedArticles = array();
       
      if ($this->related_article_urls)
      {
         $urls = explode(' ', $this->related_article_urls);
         for ($index = 0; $index < count($urls); $index++)
         {
            $relatedArticles[$index]['url'] = $urls[$index];
            $relatedArticles[$index]['title'] = str_replace('_', ' ', str_replace('wiki/', '', $urls[$index]));
         }
         return $relatedArticles;
      }
      else
      {
         return null;
      }    
   }
   
   public function setRelatedArticles()
   {
      // query google search appliance for related articles and save top 5 in | delimited text field
      
      $query = "http://216.224.126.109/search?q=".str_replace(' ','+', $this->Title->title).
               "&client=Inner_Cats&site=".ucfirst($this->Channel->slug).
               "&output=xml_no_dtd&filter=p&num=10";
          
      $xml = file_get_contents($query);

      if (preg_match_all("/<U>http:\/\/{$this->Channel->slug}.lovetoknow.com\/(.*)<\/U>/", $xml, $links, PREG_OFFSET_CAPTURE) != 0)
      {  
         foreach($links[1] as $link)
         {
            // save all but this article
            if ($link[0] != $this->Title->url)
            {
               $urls[] = $link[0];
               if (count($urls) == 5)
               {
                  break;
               }
            }
         }
         
         // return the related urls in a space delimted string to save on the article
         return implode(' ', $urls);
      }   
   }      
}