<?php

/**
 * Channel
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    LoveToKnow
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Channel extends BaseChannel
{
   public function __get($name)
   {
      if($name == 'settings')
      {
         // syntax like $object->arrayField['key'] = $value; doesnt work because the array is
         // returned by value, so we need to just disallow access to it this way entirely
         throw new Exception('Use the "getSetting()" method instead of the "settings" accessor');
      }

      return parent::__get($name);
   }

   public function getSetting($name)
   {
      $settings = $this->get('settings');
      return $settings[$name];
   }

   public function setSetting($name, $value)
   {
      $settings = $this->get('settings');
      $settings[$name] = $value;
      $this->set('settings', $settings);
   }
}
