<?php

/**
 * Image
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    LoveToKnow
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Image extends BaseImage
{
   public function genUrl($sizeName)
   {
      return "http://{$this->host}/{$this->path}/$sizeName/{$this->id}-{$this->filename}";
   }

   public function getOrigUrl()
   {
      return $this->genUrl('orig');
   }

   public function getThumbUrl()
   {
      return $this->genUrl('thumb');
   }

   public function hasSize($sizeName)
   {
      return array_key_exists($sizeName, $this->sizes);
   }
}
