<?php

/**
 * QuizContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    LoveToKnow
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class QuizContent extends BaseQuizContent
{
   const FORMAT_MULTIPLE = 1;
   const FORMAT_FREETEXT = 2;
   const FORMAT_DROPDOWN = 3;

   const DELIMITER = '|';
}
